name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  checks: write

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm i

    - name: Install Playwright Browser
      run: npx playwright install ${{ env.BROWSER }}

    - name: Run Playwright tests
      run: npx playwright test
      timeout-minutes: 5

    - name: Run Allure Action
      uses: allure-framework/allure-action@v0
      with:
        report-directory: "./test-results"
        remote-href: "https://allure-framework.github.io/allure-action/"
        github-token: ${{ secrets.GITHUB_TOKEN }}
